name: release

# run on push to main
on:
  workflow_dispatch:
  push:
    branches:
      - "main"

permissions:
  contents: write # needed to write releases
  packages: write # needed for ghcr access

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # this is important, otherwise it won't checkout the full tree (i.e. no previous tags)
      - uses: dopplerhq/secrets-fetch-action@v1.3.0
        id: doppler
        with:
          doppler-token: ${{ secrets.DOPPLER_TOKEN }}
      - uses: docker/login-action@v3 # login to ghcr
        with:
          registry: gitea.kiva.lgbt
          username: faekiva
          password:  ${{ steps.doppler.outputs.GITEA_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/bake-action@v6
        with:
          push: true
